version: "3.9"
services:
  integr_taldau:
    depends_on:
      - db
    build: .
    image: integr_taldau
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - ENV=DEV
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: integr_taldau_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data
