version: "3.9"
services:
  web:
    depends_on:
      - db
    build: .
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    volumes:
      - .:/code
    environment:
      - ENV=DEV
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: taldau_development
      POSTGRES_USER: POSTGRES_USER:-postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data
