version: "3.9"
services:
  integr_taldau:
    depends_on:
      - db
    build: .
    image: integr_taldau
    ports:
      - "8000:8000"
    environment:
      - ENV=UNIT
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: integr_taldau_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
