# Generated by Django 5.0.2 on 2024-03-14 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_dic_indexperiod_alter_chapter_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='loader.chapter', verbose_name='Раздел'),
        ),
    ]
