# Generated by Django 5.0.2 on 2024-06-10 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0004_index_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dic',
            name='term_ids',
        ),
    ]
