# Generated by Django 4.2.6 on 2024-07-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0005_remove_dic_term_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
